# Generated by Django 6.0.3 on 2026-04-06 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=50, unique=True, verbose_name='申请单号')),
                ('department', models.CharField(max_length=100, verbose_name='申请部门')),
                ('applicant', models.CharField(max_length=50, verbose_name='申请人')),
                ('application_date', models.DateField(verbose_name='申请日期')),
                ('payee_name', models.CharField(max_length=200, verbose_name='收款方户名')),
                ('payee_account', models.CharField(max_length=50, verbose_name='收款方账号')),
                ('payee_bank', models.CharField(max_length=200, verbose_name='收款方开户行')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='付款金额')),
                ('purpose', models.TextField(verbose_name='付款用途')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件列表')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('paid', '已付款'), ('verified', '已核验')], default='draft', max_length=20, verbose_name='状态')),
                ('urgent', models.BooleanField(default=False, verbose_name='是否紧急')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '付款申请',
                'verbose_name_plural': '付款申请',
                'db_table': 'payment_applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application_no'], name='payment_app_applica_fc0fde_idx'), models.Index(fields=['status'], name='payment_app_status_fb1127_idx'), models.Index(fields=['department'], name='payment_app_departm_b03eae_idx'), models.Index(fields=['application_date'], name='payment_app_applica_770942_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('approve', '通过'), ('reject', '拒绝'), ('cancel', '撤销')], max_length=20, verbose_name='操作类型')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='applications.paymentapplication', verbose_name='申请单')),
            ],
            options={
                'verbose_name': '审核日志',
                'verbose_name_plural': '审核日志',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
