# Generated by Django 6.0.3 on 2026-04-06 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=50, unique=True, verbose_name='付款单号')),
                ('actual_payee_name', models.CharField(max_length=200, verbose_name='实际收款户名')),
                ('actual_payee_account', models.CharField(max_length=50, verbose_name='实际收款账号')),
                ('actual_payee_bank', models.CharField(blank=True, max_length=200, verbose_name='实际开户行')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='实际付款金额')),
                ('payment_channel', models.CharField(choices=[('online', '网银转账'), ('counter', '柜台转账'), ('check', '支票'), ('acceptance', '承兑汇票'), ('other', '其他')], max_length=50, verbose_name='付款渠道')),
                ('bank_serial_no', models.CharField(blank=True, max_length=100, verbose_name='银行流水号')),
                ('payment_voucher', models.JSONField(blank=True, default=list, verbose_name='付款凭证')),
                ('operator', models.CharField(max_length=50, verbose_name='经办人')),
                ('payment_date', models.DateTimeField(verbose_name='付款时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='applications.paymentapplication', verbose_name='关联申请单')),
            ],
            options={
                'verbose_name': '实际付款记录',
                'verbose_name_plural': '实际付款记录',
                'db_table': 'actual_payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['payment_no'], name='actual_paym_payment_a1e568_idx'), models.Index(fields=['application'], name='actual_paym_applica_9a85e1_idx'), models.Index(fields=['payment_date'], name='actual_paym_payment_a62d69_idx')],
            },
        ),
    ]
