# Generated by Django 6.0.3 on 2026-04-06 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_match', models.BooleanField(default=False, verbose_name='是否匹配')),
                ('differences', models.JSONField(blank=True, default=list, verbose_name='差异详情')),
                ('verified', models.BooleanField(default=False, verbose_name='是否已复核')),
                ('verified_by', models.CharField(blank=True, max_length=50, verbose_name='复核人')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('verification_note', models.TextField(blank=True, verbose_name='复核说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_results', to='applications.paymentapplication', verbose_name='申请单')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_results', to='payments.actualpayment', verbose_name='付款记录')),
            ],
            options={
                'verbose_name': '对比结果',
                'verbose_name_plural': '对比结果',
                'db_table': 'comparison_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CRITICAL', '严重'), ('HIGH', '高'), ('MEDIUM', '中'), ('LOW', '低')], max_length=20, verbose_name='严重程度')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('recipients', models.JSONField(default=list, verbose_name='接收人列表')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('sent', '已发送'), ('failed', '发送失败'), ('read', '已读')], default='pending', max_length=20, verbose_name='状态')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comparison.comparisonresult', verbose_name='对比结果')),
            ],
            options={
                'verbose_name': '差异预警通知',
                'verbose_name_plural': '差异预警通知',
                'db_table': 'alert_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='comparisonresult',
            index=models.Index(fields=['is_match'], name='comparison__is_matc_839679_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonresult',
            index=models.Index(fields=['verified'], name='comparison__verifie_0e9c88_idx'),
        ),
    ]
